### ISSUE TITLE
Feature request: API Documentation

### ISSUE THREAD

**Issue by d-exclaimation** [d-exclaimation/pioneer#20]
#### Feature requested
- Improve current code documentation for public structs, classes, and functions. 
- Adding this code documentation to the online web documentation
- Tidying README to utility existing web documentation

### Motivation 

- Make it easier to use Pioneer without having to go back and forth to the documentation.
- Allow user of libraries to infer solutions to problem or create new ones by identifying the behavior described in the code documentations
- Allow better clarity for data structures,  functions, methods, properties, constant, and behavior that might not be explained explicitly anywhere

### Task

- [x] Improvement to code documentation with examples and detailed breakdown
- [x] API Reference documentation in documentation website
- [x] Cleaner README
Use this repo as an example [over-layer](https://github.com/d-exclaimation/over-layer)

**Comment by d-exclaimation** [comment]
- [ ] Improvement to code documentation with examples and detailed breakdown

**Comment by d-exclaimation** [comment]
- [ ] API Reference documentation in documentation website

**Comment by d-exclaimation** [comment]
- [ ] Cleaner README
